version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:stable"
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - emqx
      - influxdb

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0:/dev/ttyACM0
    depends_on:
      - emqx
    links:
      - "emqx"

  emqx:
    container_name: emqx
    image: "emqx/emqx:latest"
    restart: unless-stopped
    volumes:
      - ./emqx:/opt/emqx/data/mnesia
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      EMQX_NAME: edge_emqx
      EMQX_HOST: emqx

  influxdb:
    container_name: influxdb
    image: "influxdb:1.8"
    volumes:
      - ./influxdb:/var/lib/influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"

